### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by yatesco** [zcaudate/cronj#16]
Hi,

Would you please add a changelog.

Thanks!

**Comment by zcaudate** [comment]
I have with the last [commit](https://github.com/zcaudate/cronj/commit/5429be210d859c7f539361b27294c9a1cb19cbb1). Not much has changed since v1.2.1... just some superficial name changes and library upgrade. 

`cronj.core` has not changed since `v0.6.3`. The versioning have been done to keep up with the development in [hara](https://github.com/zcaudate/hara)
