### ISSUE TITLE
Correct way to import

### ISSUE THREAD

**Issue by olegakbarov** [zcaudate/cronj#17]
Total newbie to Clojure here, and i'd like to ask you what is the proper way to import `cronj`?

The only way (yeah i tried a lot) to work for me was:

```clojure
(ns starter.core
  (:require [cronj.core :refer :all])
  (:gen-class))
```

Which just dont feels right. 

Also maybe it would be usefull to add a tip about it to documentation.

Thanks!

**Comment by zcaudate** [comment]
Hey Oleg,

I’m curious if the `:gen-class` in the namespace was also required for import. 
As for your question, I don’t think there really is a *proper* way - it really depends on your personal taste.

Personally, I rarely use `:refer :all` except in testing because I prefer having the namespace explicit and have it be meaningful (to have `:as cronj` instead of `:as c`), so I tend to write code that looks something like this:

```
(ns starter.core
  (:require [cronj.core :as cronj])
  (:gen-class))

(def cnj (cronj/cronj {.. ..}))

(cronj/start cnj)
```

I know that there are articles out there saying that it's bad taste to have the namespace and the function be called the same but I quite like it so I do it all the time. Regardless, this is my personal style for code that I have control over but there are times when working with others that I will change conventions that others are used to.

I hope that answers your question =)

**Comment by olegakbarov** [comment]
Still not working this way for me :unamused:  
i'll dig deeper into docs, thanks anyway! :+1:

**Comment by zcaudate** [comment]
Hmmm… strange.

Can you put up a sample project where the code fails?

Chris.
